name: e2e
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Prepare server
        run: docker-compose -f docker-compose.dev.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker logs posthog_server
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 240